name: Update NBViewer Links

on:
  push:
    branches:
      - main

jobs:
  update_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update README.md notebook links
      uses: KensingtonOscupant/nbviewer-flush-cache-action@v1.0.4
      with:
        file_path: 'README.md'

    - name: Update README_RU.md notebook links
      uses: KensingtonOscupant/nbviewer-flush-cache-action@v1.0.4
      with:
        file_path: 'README_RU.md'